deployment:
  replicas: 2
  imageVersion: IMAGE_VERSION
  imageURL: 050451406191.dkr.ecr.us-east-1.amazonaws.com/expense/dev/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:050451406191:targetgroup/expense-dev/